global:
    scrape_interval: 10s
    evaluation_interval: 15s
scrape_configs:
  - job_name: 'demo_app_metrics'
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8081"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]